-- Insert into Students
INSERT INTO Students VALUES
(101, 'Aditi Taralgatti', 'adititaralgatti@gmail.com', '9876543210', 'Computer'),
(102, 'Siddhi Rasal', 'siddhirasal@gmail.com', '9988776655', 'ENTC');

-- Insert into Companies
INSERT INTO Companies VALUES
(1, 'Infosys', 'Pune', 'IT'),
(2, 'TCS', 'Mumbai', 'Consulting');

-- Insert into Internships
INSERT INTO Internships VALUES
(1, 101, 1, '2024-06-01', '2024-08-01', 15000),
(2, 102, 2, '2024-05-15', '2024-07-15', 12000);
